domain_path: /home2/etudiants/master2/abdennour.guessoum/tp_pwm/Vitis_pwm/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
