domain_path: /home2/etudiants/master2/abdennour.guessoum/tp_pwm/Vitis_pwm/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
